# This workflow invalidates the builds of pull requests that more than 3 hours old.
#

name: "Invalidate PRs after 3 hours"

on:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Invalidate PR Script
        run: ./invalidatePRs.sh
